# Generated by Django 4.1.6 on 2023-02-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yedekparca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spare', to='yedekparca.car'),
            preserve_default=False,
        ),
    ]
