# Generated by Django 4.1.6 on 2023-02-22 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yedekparca', '0002_alter_spare_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='customer',
        ),
        migrations.AddField(
            model_name='spare',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
