# Generated by Django 4.1.6 on 2023-02-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yedekparca', '0004_remove_spare_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='quantity',
        ),
    ]
