# Generated by Django 4.1.6 on 2023-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedekparca', '0006_spare_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='box',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
