# Generated by Django 4.1.6 on 2023-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yedekparca', '0007_spare_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='total',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
